#include "PresetState.h"

// rasterizer desc
const D3D12_RASTERIZER_DESC PresetState::m_cullNone =
{
    D3D12_FILL_MODE_SOLID,
    D3D12_CULL_MODE_NONE,
    FALSE,
    D3D12_DEFAULT_DEPTH_BIAS,
    D3D12_DEFAULT_DEPTH_BIAS_CLAMP,
    D3D12_DEFAULT_SLOPE_SCALED_DEPTH_BIAS,
    TRUE,
    FALSE,
    FALSE,
    0,
    D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF
};

const D3D12_RASTERIZER_DESC PresetState::m_wireFrame =
{
    D3D12_FILL_MODE_WIREFRAME,
    D3D12_CULL_MODE_NONE,
    FALSE,
    D3D12_DEFAULT_DEPTH_BIAS,
    D3D12_DEFAULT_DEPTH_BIAS_CLAMP,
    D3D12_DEFAULT_SLOPE_SCALED_DEPTH_BIAS,
    TRUE,
    FALSE,
    FALSE,
    0,
    D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF
};

// depth stencil op desc
const D3D12_DEPTH_STENCILOP_DESC PresetState::m_stencilDefault =
{
    D3D12_STENCIL_OP_KEEP,
    D3D12_STENCIL_OP_KEEP,
    D3D12_STENCIL_OP_KEEP,
    D3D12_COMPARISON_FUNC_ALWAYS
};

// depth stencil desc
const D3D12_DEPTH_STENCIL_DESC PresetState::m_depthReadWrite =
{
    TRUE,
    D3D12_DEPTH_WRITE_MASK_ALL,
    D3D12_COMPARISON_FUNC_LESS_EQUAL,
    FALSE,
    D3D12_DEFAULT_STENCIL_READ_MASK,
    D3D12_DEFAULT_STENCIL_WRITE_MASK,
    PresetState::m_stencilDefault,
    PresetState::m_stencilDefault
};

const D3D12_DEPTH_STENCIL_DESC PresetState::m_depthReadOnly =
{
    TRUE,
    D3D12_DEPTH_WRITE_MASK_ZERO,
    D3D12_COMPARISON_FUNC_LESS_EQUAL,
    FALSE,
    D3D12_DEFAULT_STENCIL_READ_MASK,
    D3D12_DEFAULT_STENCIL_WRITE_MASK,
    PresetState::m_stencilDefault,
    PresetState::m_stencilDefault
};

// RT blend desc
const D3D12_RENDER_TARGET_BLEND_DESC PresetState::m_rtBlendOpaque =
{
    FALSE,
    FALSE,
    D3D12_BLEND_ONE,
    D3D12_BLEND_ZERO,
    D3D12_BLEND_OP_ADD,
    D3D12_BLEND_ONE,
    D3D12_BLEND_ZERO,
    D3D12_BLEND_OP_ADD,
    D3D12_LOGIC_OP_NOOP,
    D3D12_COLOR_WRITE_ENABLE_ALL
};

const D3D12_RENDER_TARGET_BLEND_DESC PresetState::m_rtBlendAlphaBlend =
{
    TRUE,
    FALSE,
    D3D12_BLEND_SRC_ALPHA,
    D3D12_BLEND_INV_SRC_ALPHA,
    D3D12_BLEND_OP_ADD,
    D3D12_BLEND_SRC_ALPHA,
    D3D12_BLEND_INV_SRC_ALPHA,
    D3D12_BLEND_OP_ADD,
    D3D12_LOGIC_OP_NOOP,
    D3D12_COLOR_WRITE_ENABLE_ALL
};

// blend desc
const D3D12_BLEND_DESC PresetState::m_opaque =
{
    FALSE,
    FALSE,
    { 
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque,
        PresetState::m_rtBlendOpaque
    }
};

const D3D12_BLEND_DESC PresetState::m_alphaBlend =
{
    FALSE,
    FALSE,
    {
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend,
        PresetState::m_rtBlendAlphaBlend
    }
};

// static sampler desc
#define DEF_STATIC_SAMPLER(filter, addressMode, maxAnisotropy, comparison, borderColor, shaderRegister) \
    { filter, addressMode, addressMode, addressMode, 0.0f, maxAnisotropy, comparison, borderColor, 0.0f, D3D12_FLOAT32_MAX, shaderRegister, 0, D3D12_SHADER_VISIBILITY_ALL }

const D3D12_STATIC_SAMPLER_DESC PresetState::m_staticSamplers[11] = {
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_POINT,  D3D12_TEXTURE_ADDRESS_MODE_WRAP,   0,  D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 0),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_POINT,  D3D12_TEXTURE_ADDRESS_MODE_CLAMP,  0,  D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 1),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_POINT,  D3D12_TEXTURE_ADDRESS_MODE_MIRROR, 0,  D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 2),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_LINEAR, D3D12_TEXTURE_ADDRESS_MODE_WRAP,   0,  D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 3),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_LINEAR, D3D12_TEXTURE_ADDRESS_MODE_CLAMP,  0,  D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 4),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_LINEAR, D3D12_TEXTURE_ADDRESS_MODE_MIRROR, 0,  D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 5),
    DEF_STATIC_SAMPLER(D3D12_FILTER_ANISOTROPIC,        D3D12_TEXTURE_ADDRESS_MODE_WRAP,   16, D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 6),
    DEF_STATIC_SAMPLER(D3D12_FILTER_ANISOTROPIC,        D3D12_TEXTURE_ADDRESS_MODE_CLAMP,  16, D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 7),
    DEF_STATIC_SAMPLER(D3D12_FILTER_ANISOTROPIC,        D3D12_TEXTURE_ADDRESS_MODE_MIRROR, 16, D3D12_COMPARISON_FUNC_NEVER,      D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK, 8),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_LINEAR, D3D12_TEXTURE_ADDRESS_MODE_BORDER, 0,  D3D12_COMPARISON_FUNC_LESS_EQUAL, D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,      9),
    DEF_STATIC_SAMPLER(D3D12_FILTER_MIN_MAG_MIP_LINEAR, D3D12_TEXTURE_ADDRESS_MODE_BORDER, 0,  D3D12_COMPARISON_FUNC_GREATER,    D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE,     10),
};
#undef DEF_STATIC_SAMPLER